name: app_osteoartrite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.3
  youtube_player_flutter: ^9.0.1
  http: ^1.2.0
  google_fonts: ^6.2.1   
  mask_text_input_formatter: ^2.9.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  show_hide_password: ^0.0.2
  printing: ^5.11.1
  fl_chart: ^0.66.0
  intl: ^0.18.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
